# Generated by Django 4.0.3 on 2022-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0002_remove_userdata_id_userdata_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='userId',
        ),
        migrations.AddField(
            model_name='userdata',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
