# Generated by Django 4.0.3 on 2022-04-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=5)),
                ('weather', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
