# Generated by Django 4.0.3 on 2022-04-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='userId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
