# Generated by Django 4.0.3 on 2022-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0003_remove_userdata_userid_userdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userName',
            new_name='givenName',
        ),
        migrations.AddField(
            model_name='userdata',
            name='googleID',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
