# Generated by Django 4.0.3 on 2022-04-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0004_rename_username_userdata_givenname_userdata_googleid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUserData',
            fields=[
                ('googleID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('givenName', models.CharField(max_length=120)),
            ],
        ),
    ]
