# Generated by Django 4.0.3 on 2022-04-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0005_googleuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuserdata',
            name='familyName',
            field=models.CharField(default='noName', max_length=120),
            preserve_default=False,
        ),
    ]
