# Generated by Django 4.0.3 on 2022-04-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0006_googleuserdata_familyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleuserdata',
            old_name='googleID',
            new_name='googleId',
        ),
    ]
