# Generated by Django 4.0.3 on 2022-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reccomendations', '0007_rename_googleid_googleuserdata_googleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url_spotify', models.CharField(max_length=120)),
                ('playlist_img', models.CharField(max_length=120)),
                ('playlist_name', models.CharField(max_length=120)),
            ],
        ),
    ]
